; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = router, trigger, executor, controller, local

[env:local]
platform = native
test_ignore = test_controller, test_executor, test_router, test_trigger
test_filter = test_local
targets = test
[base]
; Shared configurations for all devices
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_filters = time, esp32_exception_decoder
targets = upload
check_tool = cppcheck
check_flags = 
    cppcheck: --suppress=preprocessorErrorDirective
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    '-D PMK="MONKEY_FOR_CODER"'
    '-D LMK_RT="MEN_IN_THE_HOUSE"'
    '-D LMK_RE="NEVER_THOUGHT_IT"'
    '-D LMK_RC="MASTER__SPLINTER"'
    '-D MAC_ROUTER="E8:3D:C1:8C:EF:F4"'
    '-D MAC_TRIGGER="E8:3D:C1:82:0A:38"'
    '-D MAC_EXECUTOR="10:00:3B:D5:EC:90"'
    '-D MAC_Controller="E8:3D:C1:83:8B:78"'

; --- DEVICE 1: ROUTER ---
[env:router]
extends = base
upload_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_E8:3D:C1:8C:EF:F4-if00
monitor_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_E8:3D:C1:8C:EF:F4-if00
test_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_E8:3D:C1:8C:EF:F4-if00
build_src_filter = +<router/> -<trigger/> -<executor/> -<controller/>
test_filter = test_router
test_ignore = test_local, test_controller, test_executor, test_trigger
build_flags = 
    ${base.build_flags}
    '-D DEVICE_NAME="ROUTER"'

; --- DEVICE 2: TRIGGER ---
[env:trigger]
extends = base
upload_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_E8:3D:C1:82:0A:38-if00
monitor_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_E8:3D:C1:82:0A:38-if00
test_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_E8:3D:C1:82:0A:38-if00
build_src_filter = -<router/> +<trigger/> -<executor/> -<controller/>
test_filter = test_trigger
test_ignore = test_local, test_controller, test_executor, test_router
build_flags = 
    ${base.build_flags}
    '-D DEVICE_NAME="TRIGGER"'

; --- DEVICE 3: EXECUTOR ---
[env:executor]
extends = base
upload_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_10:00:3B:D5:EC:90-if00
monitor_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_10:00:3B:D5:EC:90-if00
test_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_10:00:3B:D5:EC:90-if00
build_src_filter = -<router/> -<trigger/> +<executor/> -<controller/>
test_filter = test_executor
test_ignore = test_local, test_controller, test_router, test_trigger
build_flags = 
    ${base.build_flags}
    '-D DEVICE_NAME="EXECUTOR"'

; --- DEVICE 4: CONTROLLER ---
[env:controller]
extends = base
upload_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_E8:3D:C1:83:8B:78-if00
monitor_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_E8:3D:C1:83:8B:78-if00
test_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_E8:3D:C1:83:8B:78-if00
build_src_filter = -<router/> -<trigger/> -<executor/> +<controller/>
test_filter = test_controller
test_ignore = test_local, test_executor, test_router, test_trigger
build_flags = 
    ${base.build_flags}
    '-D DEVICE_NAME="CONTROLLER"'